# Generated by Django 3.1.2 on 2020-10-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=30)),
                ('s_age', models.IntegerField()),
                ('s_phone', models.IntegerField()),
                ('s_email', models.EmailField(max_length=254)),
                ('s_rollno', models.CharField(max_length=10)),
                ('s_add', models.CharField(max_length=50)),
                ('s_uname', models.CharField(max_length=20)),
                ('s_pass', models.CharField(max_length=20)),
            ],
        ),
    ]
